name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: fish-actions/install-fish@v1.1.0
      - name: Run tests
        run: |
          for test in tests/*.fish
              echo ===== Running $test =====
              env HOME=(mktemp -d) fish $test
          end
        shell: fish {0}
